### ISSUE TITLE
No such var: clj-antlr.static/∂ while using 

### ISSUE THREAD

**Issue by akond** [aphyr/clj-antlr#27]
I'm trying to use `clj-antlr.static/visitor` but I get an error: `No such var: clj-antlr.static/∂.`
I wonder if this namespace is maintained at all. My intention is to use a statically compiled Java parser because my project will be compiled into a JAR file. In this case, I cannot use *.g4 files anymore.

**Comment by aphyr** [comment]
Oh! That's definitely a typo--that should be (partial ...), rather than (delta-sign ...) You're probably the first person to use it in a decade, haha. Wanna try that out and make a quick PR?On Nov 21, 2023 08:10, Sergey Toropenko ***@***.***> wrote:
I'm trying to use clj-antlr.static/visitor but I get an error: No such var: clj-antlr.static/∂.
I wonder if this namespace is maintained at all?

**Comment by akond** [comment]
I'll give it a go.
